### ISSUE TITLE
Permissions With PurePerms Don‘t Work

### ISSUE THREAD

**Issue by suerion** [luca28pet/PortalsPE#10]
Hello, i had created two Portals (minigames)

When i add portalspe.portal.minigame, no one had permission.

I had tested it in the world permission and in the regulare permission?

**Comment by luca28pet** [comment]
Please use the latest release on poggit: https://poggit.pmmp.io/p/PortalsPE/
And the correct permission is portalspe.portalname

**Comment by suerion** [comment]
this is wrong, from your wiki, look at your readme

![Unbenannt](https://user-images.githubusercontent.com/55131959/81597755-81e07500-93c6-11ea-8252-26a1d4fff1e2.PNG)

**Comment by luca28pet** [comment]
the readme here on github is for a different unreleased version, refer to poggit for the release

**Comment by suerion** [comment]
sorry, on poggit, you don't had written the permission for portals

**Comment by luca28pet** [comment]
It is there in the Config section
