### ISSUE TITLE
When i will fill the Portal with particels, the client would be crash

### ISSUE THREAD

**Issue by suerion** [luca28pet/PortalsPE#12]
> [Server thread/CRITICAL]: TypeError: "Argument 4 passed to pocketmine\level\Level::setBlockIdAt() must be of the type int, string given, called in phar:///home/minecraft/multicraft/servers/PE/pocketmine/plugins/PortalsPE.phar/src/PortalsPE/Main.php on line 194" (EXCEPTION) in "src/pocketmine/level/Level" at line 2157

>[10:06:19] [Server thread/DEBUG]: #0 plugins/PortalsPE.phar/src/PortalsPE/Main(194): pocketmine\level\Level->setBlockIdAt(integer -1, integer 125, integer 110, string[28] minecraft:explosion_particle)
>[10:06:19] [Server thread/DEBUG]: #1 src/pocketmine/command/PluginCommand(54): PortalsPE\Main->onCommand(object pocketmine\Player, object pocketmine\command\PluginCommand, string[6] portal, array[2])
>[10:06:19] [Server thread/DEBUG]: #2 src/pocketmine/command/SimpleCommandMap(248): pocketmine\command\PluginCommand->execute(object pocketmine\Player, string[6] portal, array[3])
>[10:06:19] [Server thread/DEBUG]: #3 src/pocketmine/Server(1807): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\Player, string[51] portal fill sbplotwelt minecraft:explosion_particle)
>[10:06:19] [Server thread/DEBUG]: #4 src/pocketmine/Player(2218): pocketmine\Server->dispatchCommand(object pocketmine\Player, string[51] portal fill sbplotwelt minecraft:explosion_particle)
>[10:06:19] [Server thread/DEBUG]: #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(244): pocketmine\Player->chat(string[52] /portal fill sbplotwelt minecraft:explosion_particle)
>[10:06:19] [Server thread/DEBUG]: #6 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
>[10:06:19] [Server thread/DEBUG]: #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
>[10:06:19] [Server thread/DEBUG]: #8 src/pocketmine/network/mcpe/protocol/BatchPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket)
>[10:06:19] [Server thread/DEBUG]: #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
>[10:06:19] [Server thread/DEBUG]: #10 src/pocketmine/Player(3118): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
>[10:06:19] [Server thread/DEBUG]: #11 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
>[10:06:19] [Server thread/DEBUG]: #12 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[20] xxxxxxxxxxx, object raklib\protocol\EncapsulatedPacket, integer 0)
>[10:06:19] [Server thread/DEBUG]: #13 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
>[10:06:19] [Server thread/DEBUG]: #14 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
>[10:06:19] [Server thread/DEBUG]: #15 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
>[10:06:19] [Server thread/DEBUG]: #16 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
>[10:06:19] [Server thread/DEBUG]: #17 src/pocketmine/Server(2146): pocketmine\snooze\SleeperHandler->sleepUntil(double 1587974779.6659)
>[10:06:19] [Server thread/DEBUG]: #18 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
>[10:06:19] [Server thread/DEBUG]: #19 src/pocketmine/Server(1584): pocketmine\Server->start()
>[10:06:19] [Server thread/DEBUG]: #20 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[49] /home/minecraft/multicraft/servers/PE/pocketmine/, string[57] /home/minecraft/multicraft/servers/PE/pocketmine/plugins/)
>[10:06:19] [Server thread/DEBUG]: #21 src/pocketmine/PocketMine(296): pocketmine\server()
>[10:06:19] [Server thread/DEBUG]: #22 (11): require(string[104] phar:///home/minecraft/multicraft/servers/PE/pocketmine/PocketMine-MP.phar/src/p)
>[10:06:19] [Server thread/INFO]: Suerion[/xxxxxxxxxxx] loggte sich wegen "Internal server error" aus`

**Comment by benda95280** [comment]
Could you give the command used ? Have you tried with ID instead of name ?

**Comment by suerion** [comment]
/portal fill sbplotwelt minecraft:explosion_particle 

should i use the id to test?

**Comment by suerion** [comment]
> 
> 
> /portal fill sbplotwelt minecraft:explosion_particle
> 
> should i use the id to test?

https://minecraft.gamepedia.com/Particles

it is allways the same

**Comment by benda95280** [comment]
Just saying that because of :

[Server thread/CRITICAL]: TypeError: "Argument 4 passed to pocketmine\level\Level::setBlockIdAt() **must be of the type int, string given**, called in phar:///home/minecraft/multicraft/servers/PE/pocketmine/plugins/PortalsPE.phar/src/PortalsPE/Main.php on line 194" (EXCEPTION) in "src/pocketmine/level/Level" at line 2157

**Comment by suerion** [comment]
but particels are no with integer, particle id's, always in string, i don't get other id

**Comment by benda95280** [comment]
Never tried with particule, mine are full of water

**Comment by luca28pet** [comment]
Can fill with blocks only using /portal fill
